### ISSUE TITLE
mate-menu is suddenly right-aligned to its button

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/mate-menu#21]
Originally reported by: **Manni Heumann (Bitbucket: [confuseacat](https://bitbucket.org/confuseacat), GitHub: Unknown)**

----------------------------------------

I have my mate-menu icon in the upper left corner of my primary screen. Since Fedora updated to 17.10.1, clicking the menu button results in a menu that's right border is aligned to the right border of the button. In other words: the menu appears to the left of the button and with my setup that's on a different monitor.

I'm attaching a screen shot where I moved the menu button to the middle of my panel.

----------------------------------------
- Bitbucket: https://bitbucket.org/ubuntu-mate/mate-menu/issue/21

**Comment by vkareh** [comment]
I can confirm this is happening.

The position calculation when opening the menu seems to get the dimensions of the current monitor, but then calculates the offset based on the entirety of the display.

I'm planning on taking a look at this throughout the week.
