### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/mate-menu#27]
@flexiondotorg commented on [Mon Jul 24 2017](https://github.com/ubuntu-mate/mate-hud/issues/3)

MATE Menu is written using Python 3. It would be beneficial to migrate it to Python 3 so only one Python interpreter is present on the live image, therefore making the iso smaller.

**Comment by vkareh** [comment]
@flexiondotorg - finally managed to port mate-menu to Python 3, just to find out that the python bindings for [libmate-menu](https://github.com/mate-desktop/mate-menus) use Python 2 :stuck_out_tongue_closed_eyes: 

For reference: https://github.com/mate-desktop/mate-menus/issues/39

I'll take a stab at upgrading libmate-menu, but this might be a bigger project than I thought.

**Comment by flexiondotorg** [comment]
Oh heck! Sorry, that completely skipped my mind.

**Comment by raveit65** [comment]
mate-menus is done.
https://github.com/mate-desktop/mate-menus/pull/59

**Comment by vkareh** [comment]
Excellent! Thanks! I can work on porting this during the week :)

**Comment by monsta** [comment]
Actually, as https://github.com/mate-desktop/mate-menus/pull/59 is merged, you can close https://github.com/ubuntu-mate/mate-menu/pull/28 (which depends on static Python bindings) and have a look at https://github.com/ubuntu-mate/mate-menu/pull/36 + https://github.com/ubuntu-mate/mate-menu/pull/38. I think most of the work is already done there. :slightly_smiling_face:

**Comment by vkareh** [comment]
Awesome, I'll take a look. Thanks! :)
