### ISSUE TITLE
Visual bug with the bottom "end of scroll" effect

### ISSUE THREAD

**Issue by YeldhamDev** [ubuntu-mate/mate-menu#31]
When scrolling to the very end of a large section and then quickly switching to a smaller one, the "end of scroll effect" will stay on those small sections. This only happens when scrolling down.

![bug](https://user-images.githubusercontent.com/30739239/33811990-1dacc7f6-de00-11e7-8d42-462d94b21e9f.gif)

**Comment by vkareh** [comment]
I can confirm this is happening on 18.04

**Comment by flexiondotorg** [comment]
This is not a bug in MATE Menu. It is the resistance bounce animation from GTK3. Looks like the theme in use is not rendering it correctly.
