### ISSUE TITLE
Naming inconsistency

### ISSUE THREAD

**Issue by rdiez** [ubuntu-mate/mate-menu#41]
Sometimes, like in the about box, this is the "mate-menu.py". Sometimes, it is the "Advanced MATE Menu". The Preferences dialog says it's just "Menu". In the "Add to panel" list, it is called "MATE Menu".

**Comment by rdiez** [comment]
That commit was just about 1 place. Are all the other places I mentioned already fixed?

**Comment by flexiondotorg** [comment]
Yes.
