### ISSUE TITLE
Mate-menu spawns zombie processes

### ISSUE THREAD

**Issue by abcdjdj** [ubuntu-mate/mate-menu#42]
It seems that mate-menu never reaps it's child processes after they terminate, causing them to turn into zombies.

**Steps to reproduce the bug** : 
Open 'n' applications from mate-menu and watch the zombie count (in top) pile up as you close the windows one by one.

Here's the output of `ps -el | grep "defunct"` after opening 3 applications and then closing them one by one : 
`0 Z  1000 10932 10899  1  80   0 -     0 -      ?        00:00:00 atril <defunct>`
`0 Z  1000 10966 10899  0  80   0 -     0 -      ?        00:00:00 ghex <defunct>`
`0 Z  1000 10970 10899  1  80   0 -     0 -      ?        00:00:00 mate-calc <defunct>`

where `10899` is the pid of mate-menu.

**System Details**
Distribution=Arch Linux
pkgver=18.04.3

Relevant link(s) : [https://stackoverflow.com/a/16809886](url)
I did try ignoring SIGCHLD but doing so probably interferes with some library initializations and breaks the Windows (Super) Key's functionality (hide/show menu). Option 2 (double fork method) seems to be working fine on my system (for now).

**Comment by flexiondotorg** [comment]
Closed via https://github.com/ubuntu-mate/mate-menu/pull/43
