### ISSUE TITLE
[Feature Request] Add option to make mate-menu use system icon instead of custom.

### ISSUE THREAD

**Issue by darkshram** [ubuntu-mate/mate-menu#45]
Would be great to make the icon menu match the current theme every theme is switched. An option to make mate-menu use 'computer' or 'start-here' system icon and a localized text instead of custom text would be a great idea.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/ubuntu-mate/mate-menu/commit/45119cdea80183a2a1464d7686470f8dd87075ac

**Comment by pallebone** [comment]
Hi,
This change has made it impossible for me to change the icon back to ubuntu mates logo as described here: https://ubuntu-mate.community/t/help-with-minor-inconvenience-changing-theme-alters-menu-icon-dconf-exposes-no-method-of-changing/21028

Essentially it is impossible to set a different icon for the advanced mate menu even in dconf editor so now I am stuck with a non branded icon (just some dots) as opposed to having the nice mate icon. Im really sad and hoping someone can help.

Pete
