### ISSUE TITLE
New symbolic logo is nearly unvisible on light panels

### ISSUE THREAD

**Issue by raveit65** [ubuntu-mate/mate-menu#46]
Default with 19.04.1 and BlueMenta theme (default)
![Bildschirmfoto zu 2019-03-28 10-59-42](https://user-images.githubusercontent.com/961604/55149041-b608c000-5149-11e9-89e6-649b9e9f49f4.png)
Why not shipping 2 variants?
- mate-desktop.svg
- mate-desktop-symbolic.svg

You can take fresh generated icons from https://github.com/mate-desktop/mate-desktop/commit/d83bccb64d612034be471c0724edd129519c3584

**Comment by raveit65** [comment]
I replaced the icon with new regular variant from mate-desktop package.
![Bildschirmfoto zu 2019-03-28 11-20-04](https://user-images.githubusercontent.com/961604/55150039-996d8780-514b-11e9-8b51-ac3c8588e83e.png)
Looks like scaling for HIDPI needs to be added.

**Comment by flexiondotorg** [comment]
@raveit65 As discussed, this is one of the theme related issues I'd like you to sort out :wink:

**Comment by raveit65** [comment]
Not sure if this is gtk+ theme related. Where/when was is discussed?

**Comment by flexiondotorg** [comment]
@vkareh You use MATE Menu, right? :wink:

**Comment by raveit65** [comment]
Congratulation, bad logo was added be debian maintainer.
https://github.com/ubuntu-mate/mate-menu/blob/master/data/icons/mate-logo.svg
Why can nothing be done in a proper way and proper testing?

**Comment by raveit65** [comment]
I added a darker logo which can be chosen for light panels.
https://github.com/ubuntu-mate/mate-menu/pull/49

**Comment by raveit65** [comment]
![Screenshot at 2019-05-11 17-42-05](https://user-images.githubusercontent.com/961604/57571912-37739380-7414-11e9-8238-a6ffcae11992.png)
In any case HIDPI-scaling is needed.

**Comment by vkareh** [comment]
> @vkareh You use MATE Menu, right? wink

I do! Thanks for this update :) I can take a look at the HiDPI scaling if it's necessary. Seems like the SVG is 16px by default, so the code that renders it might be scaling it wrong.
