### ISSUE TITLE
Python 3.8 is breaking mate-menu.

### ISSUE THREAD

**Issue by FredBezies** [ubuntu-mate/mate-menu#67]
I'm the maintainer of mate-menu package on AUR. A comment was added related to python 3.8 compatibility. Here is a copy:

`Activating service name='org.mate.panel.applet.MateMenuAppletFactory'
requested by ':1.12' (uid=1000 pid=1683 comm="mate-panel ")
org.mate.panel.applet.MateMenuAppletFactory[1606]: No module named
'mate_menu'
Activated service 'org.mate.panel.applet.MateMenuAppletFactory'
failed: Process org.mate.panel.applet.MateMenuAppletFactory exited
with status 1`

**Comment by Rhodez-x** [comment]
Hey,  
It seems that my menu also broke during the/an upgrade.   
I removed the menu and tried a fresh install.   
  
A cording the the comment at AUR, it seems that he fixed it by:
> When I move the 'mate_menu' folder from /usr/lib/python3.7/site-packages to /usr/lib/python3.8/site-packages, starting the applet works again.  
  
But my "mate-menu" is already in the python3.8 folder, but it is not working. It is not showing in the panel, and I cannot open the menu.  
If i try to run the "mate-menu" command in the terminal, i don't get any error messages.   

Where should I see the above message if it is the same problem?

**Comment by Rhodez-x** [comment]
**FWishbringer** comment on AUR, solved my problem
(https://aur.archlinux.org/packages/mate-menu/)
> (If it doesn't exist in 3.8)
> sudo cp -r /usr/lib/python3.7/site-packages/mate* /usr/lib/python3.8/site-packages
> and
> sudo pacman -S python-cairo
> This should work. Requires python-cairo to function, must be in python3.8 site packages.

The step I missed was installation of "python-cairo"
