### ISSUE TITLE
CSS To Theme GTK

### ISSUE THREAD

**Issue by JoaquinDecima** [ubuntu-mate/mate-menu#79]
I would like to know which are the ids or the classes to be able to modify the menu with a GTK 3 theme

**Comment by isaactzab** [comment]
+1

> I would like to know which are the ids or the classes to be able to modify the menu with a GTK 3 theme

**Comment by Aravisian** [comment]
A couple ID's to get you started:
#mate-menu.background notebook, #mate-menu.background {
}

#mate-menu.background viewport {
}

#mate-menu.background > widget > box > widget > box, #mate-menu.background entry {
}
