### ISSUE TITLE
Use the default file manager, not Caja

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/mate-menu#9]
Originally reported by: **Geoffrey De Belie (Bitbucket: [Smile4ever](https://bitbucket.org/Smile4ever), GitHub: [Smile4ever](https://github.com/Smile4ever))**

----------------------------------------

MATE has a setting "Default applications". This includes a file manager as well. I have set this to PCManFM, but Caja is still used when I open a directory from inside MATE Menu.

4 options:

- Use xdg-open to open directories, fallback to caja (contrary to what I see in as a FIXME 
in mate_menu/plugins/places.py, as xdg-open is simply the most elegant solution)

- Make the file manager path customizable

- Get the default file manager from MATE settings

- Do nothing

I believe xdg-open if available is better than using Caja as default, because in MATE environments Caja will be set as the default file manager. Please let me know what you think.

----------------------------------------
- Bitbucket: https://bitbucket.org/ubuntu-mate/mate-menu/issue/9

**Comment by Smile4ever** [comment]
Any chance to get xdg-open as a default so we can close this bug?
